services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chat-service:war
    environment:
      SPRING_PROFILES_ACTIVE: prod
      API_KEYS: prod-key
      DB_URL: jdbc:postgresql://db:5432/chat
      DB_USER: chat
      DB_PASS: change-me
      CORS_ALLOWED_ORIGINS: https://your-frontend.example.com
    ports:
      - "8080:8080"
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: change-me
    ports:
      - "5432:5432"
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
