spring:
  application:
    name: chat-service
app:
  cors:
    allowed-origins: "${CORS_ALLOWED_ORIGINS:http://localhost:5173}"
  rate-limit:
    capacity: ${RATE_LIMIT_CAPACITY:60}
    refillPerMinute: ${RATE_LIMIT_REFILL_PER_MIN:60}
  api-keys: "${API_KEYS:dev-key}"
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
