spring:
  datasource:
    url: "${DB_URL}"
    username: "${DB_USER}"
    password: "${DB_PASS}"
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    com.example.chatservice: INFO
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG

app:
  cors:
    allowed-origins: "${CORS_ALLOWED_ORIGINS:https://your-frontend.example.com}"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
